name: CI-macOS

on:
  push:
    branches: [ "dev/ci-macos" ]
  pull_request:
    branches: [ "dev/ci-macos" ]

env:
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  macos:
    runs-on: macos-latest
    timeout-minutes: 10
    
    env:
      DECODER_LJ92_WORKSPACE_PATH: Decoders/LJ92/LJ92.macOS.xcodeproj
      DECODER_UNPACK_WORKSPACE_PATH: Decoders/Unpack/Unpack.macOS.xcodeproj

    steps:
    - uses: actions/checkout@v3
    
    - name: Xcode Build
      uses: sersoft-gmbh/xcodebuild-action@v2
      with:
        project: ${{env.DECODER_LJ92_WORKSPACE_PATH}}
        scheme: LJ92
        configuration: Release
        action: build
