name: CI-macOS

on:
  push:
    branches: [ "dev/ci-macos" ]
  pull_request:
    branches: [ "dev/ci-macos" ]

env:
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  macos:
    runs-on: macos-latest
    timeout-minutes: 10
    
    env:
      DECODER_LJ92_WORKSPACE_PATH: Decoders/LJ92/LJ92.macOS.xcodeproj
      DECODER_UNPACK_WORKSPACE_PATH: Decoders/Unpack/Unpack.macOS.xcodeproj
      BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
      P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
      BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}

    steps:
    - uses: actions/checkout@v3
    
    - name: "Import Certificate: Distribution"
      uses: devbotsxyz/import-signing-certificate@main
      with:
        certificate-data: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        certificate-passphrase: ${{ secrets.P12_PASSWORD }}
        keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
        
    - name: "Archive"
      uses: devbotsxyz/xcode-archive@v1
      with:
        project: ${{env.DECODER_LJ92_WORKSPACE_PATH}}
        scheme: LJ92
    
   # - name: Xcode Build
    #  uses: sersoft-gmbh/xcodebuild-action@v2
    #  with:
    #    project: ${{env.DECODER_LJ92_WORKSPACE_PATH}}
        # scheme: LJ92
    #    configuration: Release
    #    target: LJ92
    #    action: archive
