name: CI-macOS

on:
  push:
    branches: [ "dev/ci-macos" ]
  pull_request:
    branches: [ "dev/ci-macos" ]

env:
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  macos:
    runs-on: macos-latest
    timeout-minutes: 10
    
    env:
      DECODER_LJ92_WORKSPACE_PATH: Decoders/LJ92/LJ92.macOS.xcodeproj
      DECODER_UNPACK_WORKSPACE_PATH: Decoders/Unpack/Unpack.macOS.xcodeproj

    steps:
    - uses: actions/checkout@v3
    
    - name: Xcode Build
      # You may pin to the exact commit or the version.
      # uses: devbotsxyz/xcode-build@2138f429e7bebe426d65985aca0dbad5370aa697
      uses: devbotsxyz/xcode-build@v1.0.0
      with:
        # Workspace
        # workspace: ${{env.DECODER_WORKSPACE_PATH}}
        # Project
        project: ${{env.DECODER_LJ92_WORKSPACE_PATH}}
        # Scheme
        scheme: "LJ92"
        # Configuration
        configuration: "Release"
        # Code sign identity
        # code-sign-identity: # optional, default is -
