name: CI-macOS

on:
  push:
    branches: [ "dev/ci-macos" ]
  pull_request:
    branches: [ "dev/ci-macos" ]

env:
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  macos:
    name: macOS
    runs-on: macOS-12
    timeout-minutes: 10
    
    env:
      SOLUTION_FILE_PATH: Player.macOS.sln
      DECODER_WORKSPACE_PATH: Decoders/Decoders.macOS.xcworkspace
      BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
      P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
      BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      DECODER_LJ92_LIB_PATH: Decoders/LJ92/Build/Products/Release
      DECODER_UNPACK_LIB_PATH: Decoders/Unpack/Build/Products/Release
      DECODER_LJ92_ARCHIVE_PATH: Decoders/LJ92.xcarchive
      DECODER_UNPACK_ARCHIVE_PATH: Decoders/Unpack.xcarchive
      BUILD_STANDALONE_ARTIFACT_NAME: "Player-macOS-standalone"
      STANDALONE_BUILD_PATH: "${{ github.workspace }}/UI/macOS/bin/Release/OCTOPUS RAW Player.app"
      STANDALONE_BUILD_ZIP_PATH:  "${{ github.workspace }}/UI/macOS/bin/Release/OCTOPUS RAW Player.zip"
      STANDALONE_ARTIFACT_PATH: "${{ github.workspace }}/artifact/standalone"

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: 'true'
    
    - name: "Import distribution certificate"
      uses: devbotsxyz/import-signing-certificate@main
      with:
        certificate-data: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        certificate-passphrase: ${{ secrets.P12_PASSWORD }}
        keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
        
    - name: "Build LJ92 decoder native library"
      uses: devbotsxyz/xcode-archive@v1
      with:
        workspace: ${{env.DECODER_WORKSPACE_PATH}}
        scheme: LJ92
        archive-path: ${{env.DECODER_LJ92_ARCHIVE_PATH}}
        
    - name: "Build Unpack decoder native library"
      uses: devbotsxyz/xcode-archive@v1
      with:
        workspace: ${{env.DECODER_WORKSPACE_PATH}}
        scheme: Unpack
        archive-path: ${{env.DECODER_UNPACK_ARCHIVE_PATH}}
    
    - name: Prepare decoder native libraries
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        mkdir -p ${{ env.DECODER_LJ92_LIB_PATH }}
        mkdir -p ${{ env.DECODER_UNPACK_LIB_PATH }}
        cp ${{env.DECODER_LJ92_ARCHIVE_PATH}}/Products/usr/local/lib/libLJ92.dylib ${{ env.DECODER_LJ92_LIB_PATH }}
        cp ${{env.DECODER_UNPACK_ARCHIVE_PATH}}/Products/usr/local/lib/libUnpack.dylib ${{ env.DECODER_UNPACK_LIB_PATH }}

    - name: Set Xamarin version
      run: $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --mac=8.12
        
    - name: Restore NuGet packages
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}
        
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild ${{env.SOLUTION_FILE_PATH}} /t:Build /p:Configuration=Release /p:CreatePackage=false
      #/p:ArchiveOnBuild=true
      #/p:CreatePackage=true

    - name: Notarize standalone
      run: |
        /usr/bin/ditto -c -k --keepParent "${{ env.STANDALONE_BUILD_PATH }}" "${{ env.STANDALONE_BUILD_ZIP_PATH }}"
        xcrun notarytool store-credentials "AC_PASSWORD" --team-id "${{ secrets.NOTARIZATION_TEAM_ID }}" --apple-id "${{ secrets.NOTARIZATION_USERNAME }}" --password "${{ secrets.NOTARIZATION_PASSWORD }}"
        xcrun notarytool submit "${{ env.STANDALONE_BUILD_ZIP_PATH }}" --keychain-profile "AC_PASSWORD" --wait
        xcrun stapler staple "${{ env.STANDALONE_BUILD_PATH }}"

    - name: Prepare standalone artifacts
      run: |
        mkdir -p "${{ env.STANDALONE_ARTIFACT_PATH }}"
        cp -R "${{ env.STANDALONE_BUILD_PATH }}" "${{ env.STANDALONE_ARTIFACT_PATH }}"
      
    - name: Upload standalone artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        name: ${{ env.BUILD_STANDALONE_ARTIFACT_NAME }}
        path: ${{ env.STANDALONE_ARTIFACT_PATH }}
        if-no-files-found: error
