name: CI-macOS

on:
  push:
    branches: [ "dev/ci-macos" ]
  pull_request:
    branches: [ "dev/ci-macos" ]

env:
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  macos:
    runs-on: macos-latest
    timeout-minutes: 10
    
    env:
      DECODER_LJ92_WORKSPACE_PATH: Decoders/LJ92/LJ92.macOS.xcodeproj
      DECODER_UNPACK_WORKSPACE_PATH: Decoders/Unpack/Unpack.macOS.xcodeproj
      BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
      P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
      BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      DECODER_LJ92_ARCHIVE_PATH: Decoders/LJ92.xcarchive
      DECODER_UNPACK_ARCHIVE_PATH: Decoders/Unpack.xcarchive

    steps:
    - uses: actions/checkout@v3
    
    - name: "Import distribution certificate"
      uses: devbotsxyz/import-signing-certificate@main
      with:
        certificate-data: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        certificate-passphrase: ${{ secrets.P12_PASSWORD }}
        keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
        
    - name: "Archive LJ92 native library"
      uses: devbotsxyz/xcode-archive@v1
      with:
        project: ${{env.DECODER_LJ92_WORKSPACE_PATH}}
        scheme: LJ92
        archive-path: ${{env.DECODER_LJ92_ARCHIVE_PATH}}
        
    - name: "Export LJ92 native library"
      run: xcodebuild -exportArchive -archivePath ${{env.DECODER_LJ92_ARCHIVE_PATH}} -exportPath .

        
   # - name: "Export LJ92 native library"
   #   uses: devbotsxyz/xcode-export-archive@main
   #   with:
   #     project: ${{env.DECODER_LJ92_WORKSPACE_PATH}}
   #     scheme: LJ92
   #     archive-path: ${{ github.workspace }}/${{env.DECODER_LJ92_ARCHIVE_PATH}}
   #     export-path: ${{ github.workspace }}/Decoders/
