name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_CONFIGURATION: Release
  BUILD_ARTIFACT_NAME: "OCTOPUS RAW Player"

permissions:
  contents: read

jobs:
  build-windows-x64:
    name: Build Windows x64
    runs-on: windows-latest
    
    env:
      SOLUTION_FILE_PATH: Player.Windows.sln
      PROJECT_FILE_PATH: UI/Windows/Player.UI.Windows.csproj
      ARTIFACT_PATH: "bin/Release/net6.0-windows/publish/"
      BUILD_PLATFORM: x64

    steps:
    - uses: actions/checkout@v3

    - uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild -t:restore ${{env.SOLUTION_FILE_PATH}} -p:PublishReadyToRun=true

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} ${{env.SOLUTION_FILE_PATH}}
      
    - name: Publish
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /t:publish /p:RuntimeIdentifier=win-x64 /p:PublishDir="${{env.ARTIFACT_PATH}}" /p:IncludeNativeLibrariesForSelfExtract=true /p:SelfContained=true /p:PublishSingleFile=true /p:PublishReadyToRun=true /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} ${{env.PROJECT_FILE_PATH}}
  
    - name: Upload artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        name: ${{env.BUILD_ARTIFACT_NAME}}
        path: ${{env.GITHUB_WORKSPACE}}/${{env.ARTIFACT_PATH}}
      
