name: Release

on:
  push:
    branches: [ "releases/**" ]
  pull_request:
    branches: [ "releases/**" ]

env:
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    timeout-minutes: 15
    
    env:
      SOLUTION_FILE_PATH: Player.Windows.sln
      PROJECT_FILE_PATH: UI/Windows/Player.UI.Windows.csproj
      INSTALLER_PROJECT_PATH: Installer/Installer.vdproj
      PUBLISH_PATH: "bin/Release/net6.0-windows/publish/"
      STANDALONE_ARTIFACT_PATH: "${{ github.workspace }}\\UI\\Windows\\bin\\Release\\net6.0-windows\\publish\\"
      INSTALLER_ARTIFACT_PATH: "${{ github.workspace }}\\Installer\\"
      BUILD_PLATFORM: x64
      BUILD_STANDALONE_ARTIFACT_NAME: "Player-win64-standalone"
      BUILD_INSTALLER_ARTIFACT_NAME: "Player-win64-installer"

    steps:
    - uses: actions/checkout@v3

    - uses: microsoft/setup-msbuild@v1.0.2
    - uses: seanmiddleditch/gha-setup-vsdevenv@v4

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild -t:restore ${{env.SOLUTION_FILE_PATH}} -p:PublishReadyToRun=true

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} ${{env.SOLUTION_FILE_PATH}}
      
    - name: Publish
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /t:publish /p:RuntimeIdentifier=win-x64 /p:PublishDir="${{env.PUBLISH_PATH}}" /p:IncludeNativeLibrariesForSelfExtract=true /p:SelfContained=true /p:PublishSingleFile=true /p:PublishReadyToRun=true /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} ${{env.PROJECT_FILE_PATH}}
  
    - name: Upload standalone artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        name: ${{env.BUILD_STANDALONE_ARTIFACT_NAME}}
        path: "${{ env.STANDALONE_ARTIFACT_PATH }}*.exe"
        if-no-files-found: error
    
    # Required to Build VS Installer Projects
    - run: .\DisableOutOfProcBuild.exe
      working-directory: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild

    - name: Create Installer
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: DevEnv ${{env.INSTALLER_PROJECT_PATH}} /build ${{env.BUILD_CONFIGURATION}}

    - name: Upload installer artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        name: ${{env.BUILD_INSTALLER_ARTIFACT_NAME}}
        path: "${{ env.INSTALLER_ARTIFACT_PATH }}*.msi"
        if-no-files-found: error
